### ISSUE TITLE
Is this library usable at the moment?

### ISSUE THREAD

**Issue by Tuo-ZHANG** [eb4j/mdict4j#54]
Hi, I have followed this project for a while because I am also interested in dictionary development with mdict. Just want to ask if this library is already usable at this moment. If so, could you possibly give some short documentation on how to use it? Thanks in advance!

**Comment by miurahr** [comment]
You can find a project EBViewer that use mdict4j
Here is an example how to use.
https://github.com/eb4j/ebviewer/blob/main/src/main/java/io/github/eb4j/ebview/dictionary/MDict.java

**Comment by miurahr** [comment]
I've add a document.

Please run a build command and see a built result at `build/site/index.html`.

```bash
./gradlew sphinx
```

**Comment by Tuo-ZHANG** [comment]
> I've add a document.
> 
> Please run a build command and see a built result at `build/site/index.html`.
> 
> ```shell
> ./gradlew sphinx
> ```
> 
> or just see document source at https://github.com/eb4j/mdict4j/tree/main/docs

cool, many thanks for the reply!

**Comment by miurahr** [comment]
@Tuo-ZHANG you can now access document at https://mdict4j.readthedocs.io/en/latest/

 if you are ok, could give us a documentation translation in your mother language?
You can find a translation files at  https://github.com/eb4j/mdict4j/tree/main/docs/locale/

mdict is popular in China, and unfortunately I'm not fluent with Chinese, I can talk only a phrase "请给我一瓶🍺 啤酒!" in restaurant  😄

**Comment by Tuo-ZHANG** [comment]
> @Tuo-ZHANG you can now access document at https://mdict4j.readthedocs.io/en/latest/
> 
> if you are ok, could give us a documentation translation in your mother language? You can find a translation files at https://github.com/eb4j/mdict4j/tree/main/docs/locale/
> 
> mdict is popular in China, but I'm not fluent with Chinese, I can talk only a phrase "请给我一瓶🍺 啤酒!" in restaurant 😄

hi, I could help, but I am not sure what I should do though, you can specify the exact steps need to be taken to me

**Comment by miurahr** [comment]
## Steps

1. Fork the project repository
2. Clone the repository
3. Go to directory `docs/locale/zh_CN/LC_MESSAGES/`
4. Open `index.po` in editor
5. Edit `msgstr` sting in local language
6. same for `hwotouse.po`
7. commit and send pull-request

## Tool

You can use any editor for translation, but there are some tools to handle PO file.
[poedit](https://poedit.net/) is a candidate to edit PO file. It is multi-platform tool and has good GUI.
The tool help you not to break file format, and check integrity.
